ignore:
  - 'Mini Model <minimodel@metamodel.me>'
  - 'Scrutinizer Auto-Fixer <auto-fixer@scrutinizer-ci.com>'

exclude:
  - /^contao\/languages/

mapping:
  'Andreas Isaak <info@andreas-isaak.de>': 'Andreas Isaak <andy.jared@googlemail.com>'
