services:
  metamodels.attribute_translatedalias.factory:
    class: MetaModels\AttributeTranslatedAliasBundle\Attribute\AttributeTypeFactory
    arguments:
      - "@database_connection"
      - "@event_dispatcher"
    tags:
      - { name: metamodels.attribute_factory }

  metamodels.attribute_translatedalias.listeners.translated_alias_options:
    class: MetaModels\AttributeTranslatedAliasBundle\EventListener\TranslatedAliasOptionsListener
    arguments:
      - '@metamodels.factory'
    tags:
      - { name: kernel.event_listener, event: men-at-work.multi-column-wizard-bundle.get-options, method: getOptions }

  metamodels.attribute_translatedalias.listeners.prepostfix_fields:
    class: MetaModels\AttributeTranslatedAliasBundle\EventListener\PrepostFixFieldsListener
    arguments:
      - "@cca.dc-general.scope-matcher"
      - "@metamodels.factory"
      - "@translator"
    tags:
      - name: kernel.event_listener
        event: dc-general.view.contao2backend.build-widget
        method: buildWidget
        priority: 100
      - name: kernel.event_listener
        event: dc-general.view.contao2backend.decode-property-value-for-widget
        method: decodeValue
      - name: kernel.event_listener
        event: dc-general.view.contao2backend.encode-property-value-from-widget
        method: encodeValue
